name: Emeralds
description: Emeralds
author: hazae41
version: 1.0
api-version: 1.16
main: hazae41.emeralds.Main
commands:
  "$":
    aliases: [ "money", "emeralds" ]
    description: Money
    usage: /$